- name: Configuring hadoop
  hosts: hadoop
  tasks:
  - name: Creating Directory for installation
    file:
       name: /root/hadoop1
       state: directory

  - name: Copying java package
    copy: 
       src: /root/jdk-8u171-linux-x64.rpm  
       dest: /root/hadoop1/

  - name: Copying hadoop package
    copy:
       src:  /root/hadoop-1.2.1-1.x86_64.rpm 
       dest: /root/hadoop1/

  - name: Installing java
    command: 
       cmd: "rpm -i /root/hadoop1/jdk-8u171-linux-x64.rpm"

  - name: Installing hadoop 
    command: 
       cmd: "rpm -i /root/hadoop1/hadoop-1.2.1-1.x86_64.rpm --force"
       
  - name: Editing core-site.xml
    lineinfile:
       path:  "/etc/hadoop/core-site.xml"
       insertafter: "^<configuration>"
       firstmatch: yes
       line: "{{ item }}"
       state: present
    with_items:
    - '<property>'
    - '<value>hdfs://master:9001</value>'
    - '<name>fs.default.name</name>'
    - '</property>'

  - name: Creating namenode directory
    file:
       dest: /root/hadoop1/hdfs/namenode
       state: directory
    when: inventory_hostname in groups["master-hadoop"]

  - name: Creating datanode directory
    file:
       dest: /root/hadoop/hdfs/datanode
       state: directory
    when: inventory_hostname in groups["slaves-hadoop"]

  - name: Editing hdfs-site.xml
    lineinfile:
       path:  "/etc/hadoop/hdfs-site.xml"
       insertafter: "^<configuration>"
       firstmatch: yes
       line: "{{ item }}"
       state: present
    with_items:
    - '</property>' 
    - '<value>/root/hadoop/hdfs/namenode</value>'
    - '<name>dfs.data.dir</name>'
    - '<property>'
    when: inventory_hostname in groups["master-hadoop"]

  - name: Editing hdfs-site.xml
    lineinfile:
       path:  "/etc/hadoop/hdfs-site.xml"
       insertafter: "^<configuration>"
       firstmatch: yes
       line: "{{ item }}"
       state: present
    with_items:
    - '</property>'
    - '<value>/root/hadoop/hdfs/datanode</value>'
    - '<name>dfs.data.dir</name>'
    - '<property>'
    when: inventory_hostname in groups["slaves-hadoop"]
   
  - name: Formatting the namenode 
    command: 
       cmd: "echo 'Y' | hadoop namenode -format"

  - name: Starting the namenode
    command: 
       cmd: "hadoop-daemon.sh start namenode"
    when: inventory_hostname in groups["master-hadoop"] 

  - name: Starting the datanode 
    command: 
        cmd: "hadoop-daemon.sh start datanode"
     
 
